spring:
  datasource:
    url: jdbc:oracle:thin:@14.29.116.237:1521:orcl
    username: slfh
    password: slfh
    driver-class-name: oracle.jdbc.driver.OracleDriver
  application:
      name: businessclient
  eureka:
    client:
      service-url:
         defultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8088
logging:
  level:
    com:
      southwind:
        businessclient:
            controller: DEBUG
            dao: DEBUG
            service: DEBUG
  file:
    path: log